django_project/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/follow/', views.follow, name='follow')
]

django_project/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/like/', views.likes, name='likes'),
    
]

django_project/crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/crud/templates/base.html
{% load bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% bootstrap_css %}
  <title>Document</title>
</head>
<body>
  {% include 'nav.html' %}
  <div class="container">

    {% block content %}
    {% endblock %}
  </div>
  {% bootstrap_javascript %}
  <script src="https://kit.fontawesome.com/699ef5ec6e.js" crossorigin="anonymous"></script>
</body>
</html>

django_project/crud/templates/nav.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'articles:index' %}">
      <img src="{% static 'JayMaro.png' %}" alt="" width="30" height="24" class="d-inline-block align-text-top">
      Homepage
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active btn btn-light" aria-current="page" href="{% url 'articles:create' %}">Create</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active btn btn-light" aria-current="page" href="{% url 'accounts:profile' request.user.username %}">My Profile</a>
          </li>
          <a class="nav-link active btn btn-light" href="{% url 'accounts:update' %}">Update Self</a>
          <form class="nav-link active btn btn-light" action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-warning btn-sm" type="submit">Logout</button>
          </form>
          <form class="nav-link active btn btn-light" action="{% url 'accounts:delete' %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-danger btn-sm" type="submit">탈퇴</button>
          </form>
        {% else %}
          <li class="nav-item">
            <a class="nav-link disabled btn btn-light" aria-current="page" href="{% url 'accounts:login' %}">새 글을 작성하려면 로그인하세요.</a>
          </li>
          <a class="nav-link btn btn-light" href="{% url 'accounts:login' %}">Login</a>
          <a class="nav-link btn btn-light" href="{% url 'accounts:signup' %}">Signup</a>
        {% endif %}


      </ul>
      <div class="text-end">
        Hello, {{ request.user }}
      </div>
    </div>
  </div>
</nav>